### PR TITLE
Enable new ax

### PR DESCRIPTION
**Pull request by shuds13**
A continuation of #239

I have got the tests to work with Ax 0.5.0+. 

Due to the number of code changes in that release,  I suggest we require this is a minimal version.

- [ ] Should be checked by user of Ax genertors. 

Note there is also still quite a number of warnings, mostly deprecation warnings from dependencies.

## Details

- [x] The multitask example has been updated and now works in the Standalone example.
- I don't know if all the new fields in MT_MTGP_trans are necessary 

- [x] The Single Fidelity example also needs updates for Ax 0.5.0 

- It looks like the different models [GPEI, MOO have been replaced by  BOTORCH_MODULAR (and  FULLYBAYESIANMOO/ FULLYBAYESIAN by SAASBO)](https://github.com/facebook/Ax/blob/main/ax/storage/json_store/decoder.py#L77), which apparently infers acquisition function from the optimization config (e.g.,  the number of objectives).  The single fidelity test runs with this.

- [x] test_ax_generators.py:

- [x] This change is also required in test_ax_generators.py

```
            # assert df["generation_method"].to_numpy()[-1] == "GPEI"
            assert df["generation_method"].to_numpy()[-1] == "BoTorch"
```

- [x] Fails in  test_ax_generators.py -> test_ax_multi_fidelity():
TypeError: Unexpected keyword argument `X_pending` when constructing input arguments for construct_inputs_qMFKG.' Similar for constraints. It runs if I remove these  from `acquisition_options`.

- [x] In test test_ax_service_init() `assert df["generation_method"][j] == "Manual"` fails, getting `None` instead for the user added trial. It seems to happen since `_maybe_transition_to_next_node()` is called (previously `_maybe_move_to_next_step()`) in _optimas/generators/ax/service.base.py_ and `generation_methods.add("Manual")` in Ax's report_utils.py does not get run. For now, changed test to expect `None` but this should be checked. Otherwise test seems to function correctly with these trials replacing the sobol steps.

see:
https://github.com/facebook/Ax/releases/tag/0.5.0 (fifth bullet).
https://ax.dev/docs/models/ (using BOTORCH_MODULAR)

### CODE REVIEW

File: optimas/generators/ax/developer/multitask.py [hunk 1]
```diff
@@ -37,13 +68,81 @@
...
+def get_MTGP(
+    experiment: Experiment,
+    data: Data,
+    search_space: Optional[SearchSpace] = None,
+    trial_index: Optional[int] = None,
+    device: torch.device = torch.device("cpu"),
+    dtype: torch.dtype = torch.double,
+) -> TorchModelBridge:
+    """Instantiates a Multi-task Gaussian Process (MTGP) model that generates
+    points with EI.
```
Comment (ax3l) [inline optimas/generators/ax/developer/multitask.py:89]: CI seems to request a small formatting change here:
```
pydocstyle...............................................................Failed
- hook id: pydocstyle
- exit code: 1

optimas/generators/ax/developer/multitask.py:88 in public function `get_MTGP`:
        D202: No blank lines allowed after function docstring (found 1)
optimas/generators/ax/developer/multitask.py:88 in public function `get_MTGP`:
        D205: 1 blank line required between summary line and description (found 0)
optimas/generators/ax/developer/multitask.py:88 in public function `get_MTGP`:
        D400: First line should end with a period (not 's')
optimas/generators/ax/developer/multitask.py:88 in public function `get_MTGP`:
        D401: First line should be in imperative mood (perhaps 'Instantiate', not 'Instantiates')
```

**Review by RemiLehe — APPROVED** [review]

**Comment by ax3l** [comment]
Thank you, that's great!!
